
# 启动端口号
server:
  post: 8000

# MySQL数据源配置
mysql:
  username: root
  password: 123456
  url: tcp(localhost:3306)/awesome?charset=utf8&parseTime=True&loc=Local


# JWT配置
jwt:
  signingKey: z3d6k8v0n3w7m9sa1fd0u09h

# 微信小程序相关配置
code2Session:
  appId:
  appSecret: